version: 0.0

os: linux

files:
  - source: java-all-ways-to-iterate-0.0.1-SNAPSHOT.jar
    destination: /tmp

hooks:
  # -------------------------------------------------------
  # Runs BEFORE the new revision is downloaded from artifact storage (S3 in our case)
  # Use for: stopping old app
  # -------------------------------------------------------
  ApplicationStop:
    - location: stop-process.sh
      timeout: 60
      runas: root

  # -------------------------------------------------------
  # Runs AFTER ApplicationStop, Executes BEFORE files are copied
  # from /opt/codedeploy-agent/deployment-root/<deployment-group-id>/<deployment-id>/deployment-archive/
  # to the destination you specify in "files" section above (/tmp in our case)
  #
  # Note: AWS does the copy from S3 to /opt due to "DownloadBundle" phase (only AWS can)
  # Use for: removing old artifact, cleaning temp files.
  # If we remove the existing application from target directory in before-install.sh
  # then we dont have to select option "Overwrite the content" under optional content options
  # in aws codedeploy web console
  # -------------------------------------------------------
  BeforeInstall:
    - location: before-install.sh
      timeout: 60
      runas: root

  # -------------------------------------------------------
  # Runs AFTER files are copied to destination
  # Use for: setting permissions, moving files, config setup, read params/secrets
  # from Secrets Manager, Parameter Store
  #
  # Note: AWS only will execute the "Install" phase which AWS actually perform the 
  # copy of files from source 
  # opt/codedeploy-agent/deployment-root/<deployment-group-id>/<deployment-id>/deployment-archive/
  # to the destination you specify in "files" section above (/tmp in our case)
  # -------------------------------------------------------
  AfterInstall:
    - location: after-install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start-process.sh
      timeout: 60
      runas: root
