version: 0.0

os: linux

files:
  - source: java-all-ways-to-iterate-0.0.1-SNAPSHOT.jar
    destination: /tmp

hooks:
  # -------------------------------------------------------
  # Runs BEFORE the new revision is downloaded from artifact storage (S3 in our case)
  # Use for: stopping old app
  # -------------------------------------------------------
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: root
