version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  springboot-junit-iterations-demo-reports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    discard-paths: no
    file-format: JUNITXML
artifacts:
  files:
    - target/java-all-ways-to-iterate-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - start-process.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
